ALTER TABLE users 
ADD COLUMN IF NOT EXISTS hashed_password VARCHAR(255) NULL;
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS must_reset_password BOOLEAN DEFAULT TRUE;
ALTER TABLE users 
ALTER COLUMN is_active SET DEFAULT TRUE;
ALTER TABLE users 
ALTER COLUMN is_active SET NOT NULL;